# Generated by Django 2.2.8 on 2019-12-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('media', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('NBA', 'National Basketball Association'), ('NFL', 'National Football League')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_abbr', models.CharField(max_length=4, unique=True)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berita_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espn.Berita')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espn.Team')),
            ],
        ),
    ]
