# Generated by Django 2.2.8 on 2019-12-12 12:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='media',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=''),
        ),
    ]
