# Generated by Django 2.2.8 on 2019-12-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0002_auto_20191212_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('NBA', 'National Basketball Association'), ('NFL', 'National Football League')], max_length=11)),
                ('takes_time', models.DateTimeField()),
                ('ht_score', models.IntegerField(blank=True)),
                ('at_score', models.IntegerField(blank=True)),
                ('done', models.IntegerField()),
                ('away_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_id', to='espn.Team')),
                ('home_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_id', to='espn.Team')),
            ],
        ),
    ]
