# Generated by Django 2.2.8 on 2019-12-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0003_auto_20191212_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_id_tes', to='espn.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_id_tes', to='espn.Team'),
        ),
    ]
